service: users
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs16.x
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    NODE_OPTIONS: --enable-source-maps --stack-trace-limit=1000 --experimental-modules --es-module-specifier-resolution=node
    DATABASE_URL: ${env:DATABASE_URL}
    AUTH_MS_URL: ${env:AUTH_MS_URL}
    JWT_SECRET: ${env:JWT_SECRET}

useDotenv: true

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: "*"

package:
  individually: true

plugins:
  - serverless-offline
  - serverless-plugin-typescript
