service: users-crud
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs16.x
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    NODE_OPTIONS: --enable-source-maps --stack-trace-limit=1000 --experimental-modules --es-module-specifier-resolution=node
    DATABASE_URL: ${env:DATABASE_URL}

useDotenv: true

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: "*"

package:
  patterns:
    - src/**
    - handler.ts
    - "!.git/**"
  individually: true

plugins:
  - serverless-offline
  - serverless-plugin-typescript
